import type { Metadata } from "next";
import { Geist, Geist_Mono, Jersey_10 } from "next/font/google";
import "./globals.css";
import Navbar from "@/componenets/Navbar";
import SnakeBackground from "@/componenets/SnakeGame";
import Footer from "@/componenets/footer";
import Lightning from "@/componenets/Lightning";
import Preloader from "@/componenets/Preloader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ ADD THIS
const jersey = Jersey_10({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jersey",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        ${jersey.variable} 
        h-full antialiased
      `}
    >
      <body
        suppressHydrationWarning
        className="h-[100dvh] overflow-hidden border-3  border-dashed border-cyan-400 bg-[var(--surface-bg)] text-white flex flex-col font-jersey relative"
      >
        <Preloader />
        <SnakeBackground />
        <Lightning />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
